package main

import (
	"bytes"
	"encoding/binary"
	"errors"
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
	"golang.org/x/sys/unix"
)

func main() {	

	// Subscribe to signals for terminating the program.
	stopper := make(chan os.Signal, 1)
	signal.Notify(stopper, os.Interrupt, syscall.SIGTERM)

	// Allow the current process to lock memory for eBPF resources.
	if err := rlimit.RemoveMemlock(); err != nil {
		log.Fatal(err)
	}

	// Load pre-compiled programs and maps into the kernel.
	objs := bpfObjects{}
	if err := loadBpfObjects(&objs, nil); err != nil {
		log.Fatalf("loading objects: %v", err)
	}
	defer objs.Close()

	
	kp, err := link.Tracepoint("syscalls","sys_enter_mount",objs.MountEntry,nil)
	if err != nil {
		log.Fatalf("opening kprobe: %s", err)
	}
	defer kp.Close()

	// kp2, err := link.Tracepoint("syscalls","sys_exit_mount",objs.MountExit,nil)
	// if err != nil {
	// 	log.Fatalf("opening kprobe: %s", err)
	// }
	// defer kp2.Close()

	// kp3, err := link.Tracepoint("syscalls","sys_enter_umount",objs.UmountEntry,nil)
	// if err != nil {
	// 	log.Fatalf("opening kprobe: %s", err)
	// }
	// defer kp3.Close()

	// kp4, err := link.Tracepoint("syscalls","sys_exit_umount",objs.UmountExit,nil)
	// if err != nil {
	// 	log.Fatalf("opening kprobe: %s", err)
	// }
	// defer kp4.Close()

	// Open a ringbuf reader from userspace RINGBUF map described in the
	// eBPF C program.
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		log.Fatalf("opening ringbuf reader: %s", err)
	}
	defer rd.Close()

	// Close the reader when the process receives a signal, which will exit
	// the read loop.
	go func() {
		<-stopper

		if err := rd.Close(); err != nil {
			log.Fatalf("closing ringbuf reader: %s", err)
		}
	}()

	log.Println("Waiting for events..")

	// bpfEvent is generated by bpf2go.
	var event bpfEvent
	for {
		record, err := rd.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				log.Println("Received signal, exiting..")
				return
			}
			log.Printf("reading from reader: %s", err)
			continue
		}

		// Parse the ringbuf event entry into a bpfEvent structure.
		if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &event); err != nil {
			log.Printf("parsing ringbuf event: %s", err)
			continue
		}
		
		commBytes := make([]byte, len(event.Comm))
		for i, v := range event.Comm {
			commBytes[i] = byte(v)
		}
		log.Printf("pid: %d\tcomm: %s\n", event.Pid, unix.ByteSliceToString(commBytes))
		
		fsBytes := make([]byte, len(event.Fs))
		for i, v := range event.Fs {
			fsBytes[i] = byte(v)
		}
		log.Printf("pid: %d\t fs: %s\n", event.Pid, unix.ByteSliceToString(fsBytes))

		srcBytes := make([]byte, len(event.Src))
		for i, v := range event.Src {
			srcBytes[i] = byte(v)
		}
		log.Printf("pid: %d\t src: %s\n", event.Pid, unix.ByteSliceToString(srcBytes))

		destBytes := make([]byte, len(event.Dest))
		for i, v := range event.Dest {
			destBytes[i] = byte(v)
		}
		log.Printf("pid: %d\t dest: %s\n", event.Pid, unix.ByteSliceToString(destBytes))
		
		dataBytes := make([]byte, len(event.Data))
		for i, v := range event.Data {
			dataBytes[i] = byte(v)
		}
		log.Printf("pid: %d\t data: %s\n", event.Pid, unix.ByteSliceToString(dataBytes))

	}
}
